name: Deploy Static Site Infrastructure

on:
  push:
    branches: [ main, dev, staging ]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terragrunt-plan:
    name: Terragrunt Plan
    runs-on: ubuntu-latest

    env:
      TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          curl -sL https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Terragrunt Init
        run: |
          cd ./infrastructure/modules/static_site
          terragrunt init

      - name: Terragrunt Plan
        run: |
          cd ./infrastructure/modules/static_site
          terragrunt plan

  manual-approval:
    name: Manual Approval Gate
    runs-on: ubuntu-latest
    needs: terragrunt-plan

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ steps.generate_token.outputs.token }}
          approvers: ci-waracle-challenge
          minimum-approvals: 1

  terragrunt-apply:
    name: Terragrunt Apply
    runs-on: ubuntu-latest
    needs: manual-approval

    env:
      TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
      TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
      TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Install Terragrunt
        run: |
          curl -sL https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64 -o terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Terragrunt Init
        run: |
          cd ./infrastructure/modules/static_site
          terragrunt init

      - name: Terragrunt Apply
        run: |
          cd ./infrastructure/modules/static_site
          terragrunt apply -auto-approve